language: java
deploy:
  edge: true
  provider: cloudfoundry  
  username: talk2jamesraj@yahoo.com
  password: sacsb4u!
  api: https://api.run.pivotal.io
  organization: letustry
  space: development


