language: java
deploy:
  edge: true
  provider: cloudfoundry  
  username: talk2jamesraj@yahoo.com
  password: james123
  api: https://api.run.pivotal.io
  organization: myawesomeorganization
  space: staging


